#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

#General
bspc config split_ratio               0.5
bspc config focus_follows_pointer     true
bspc config pointer_modifier          mod4

#Appearance
bspc config top_padding               6
bspc config bottom_padding            6
bspc config left_padding              6
bspc config right_padding             6

#bspc config border_width              3
bspc config window_gap                6

#bspc config normal_border_color       "#B54B51"
#bspc config active_border_color       "#3B1815"
#bspc config focused_border_color      "#D95A4E"
#bspc config presel_feedback_color     "#8C3A32"


bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config single_monocle            true

bspc config focus_follows_pointer     true
bspc config pointer_motion_interval   5
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

sxhkd &
picom -b --config /home/jose/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
sxhkd &


###############################################
############BASICO PARA FUNCIONAR##############
#
#pgrep -x sxhkd > /dev/null || sxhkd &
#
#bspc monitor -d I II III IV V VI VII VIII IX X
#
#
#bspc config border_width         2
#bspc config window_gap          12
#
#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#sxhkd &
#picom --config ~/.config/picom/picom.desktop &
#nitrogen &
#dunst &
#polybar &
#sxhkd &

