#!/bin/bash

#Boot
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#General
bspc config split border_width    0
bspc config focused_border_color    \#C0C0C0
bspc config normal_border_color    \#999999
bspc config gapless_monocle     true
bspc config window_gap    6

#Pointer actions
bspc config pointer_action1    move
bspc config pointer_action2    resize_side
bspc config pointer_action3    resize_corner
bsoc config pointer_modifier   mod1
bspc config focus_follows_pointer    true

#run,etc...
sxhkd &
picom -b --config /home/jose/.config/picom/picom.conf &
polybar &
feh --bg-scale /home/$USER/.config/feh/wallpaper.png &
