#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X


#OI
#General
bspc config window_gap                6
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        false
bspc config gapless_monocle           false

#Config Mouse
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_montion_interval  5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

sxhkd &
picom --config ~/.config/picom/picom.desktop &
nitrogen &
dunst &
polybar &
sxhkd &


###############################################
############BASICO PARA FUNCIONAR##############
#
#pgrep -x sxhkd > /dev/null || sxhkd &
#
#bspc monitor -d I II III IV V VI VII VIII IX X
#
#
#bspc config border_width         2
#bspc config window_gap          12
#
#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#sxhkd &
#picom --config ~/.config/picom/picom.desktop &
#nitrogen &
#dunst &
#polybar &
#sxhkd &

